'use strict';
function beadPatternFromImage(img,width,height,removeWhite=false,crop=null,smoothing=0){
 if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>300||height>300)throw Error('Choose dimensions between 1 and 300.');
 const c=document.createElement('canvas');c.width=width;c.height=height;const g=c.getContext('2d',{willReadFrequently:true});g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';const area=crop||{x:0,y:0,width:img.width,height:img.height};const scale=Math.min(width/area.width,height/area.height),w=area.width*scale,h=area.height*scale;g.drawImage(img,area.x,area.y,area.width,area.height,(width-w)/2,(height-h)/2,w,h);const data=g.getImageData(0,0,width,height).data,palette=[],indices=new Map();

 const strength=Math.max(0,Math.min(100,Number(smoothing)||0));
 if(strength>0){
  const visible=i=>data[i+3]>=128&&!(removeWhite&&data[i]>242&&data[i+1]>242&&data[i+2]>242);
  for(let pass=0;pass<(strength>65?2:1);pass++){
   const original=new Uint8ClampedArray(data),threshold=15+strength*1.5;
   for(let y=0;y<height;y++)for(let x=0;x<width;x++){
    const i=(y*width+x)*4;if(!visible(i))continue;
    const channels=[[],[],[]];
    for(let yy=Math.max(0,y-1);yy<=Math.min(height-1,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(width-1,x+1);xx++){const j=(yy*width+xx)*4;if(!visible(j))continue;for(let k=0;k<3;k++)channels[k].push(original[j+k]);}
    if(channels[0].length<3)continue;
    const median=channels.map(a=>a.sort((a,b)=>a-b)[Math.floor(a.length/2)]);
    const difference=Math.sqrt(median.reduce((sum,v,k)=>sum+(v-original[i+k])**2,0)/3);
    if(difference<=threshold)for(let k=0;k<3;k++)data[i+k]=Math.round(original[i+k]+(median[k]-original[i+k])*strength/100);
   }
  }
 }
 const grid=Array.from({length:height},(_,y)=>Array.from({length:width},(_,x)=>{const i=(y*width+x)*4;if(data[i+3]<128||(removeWhite&&data[i]>242&&data[i+1]>242&&data[i+2]>242))return null;const colour=nearestHama(hex(data[i],data[i+1],data[i+2]));if(!indices.has(colour.hama)){const index=palette.length;indices.set(colour.hama,index);palette.push({hama:colour.hama,name:colour.name,color:colour.color,code:index<26?String.fromCharCode(65+index):'C'+(index+1)});}return indices.get(colour.hama);}));
 if(!palette.length)throw Error('No visible beads found. Try disabling “Remove near-white background”.');return {width,height,palette,grid};
}
function beadOccupiedBounds(grid){let left=Infinity,top=Infinity,right=-1,bottom=-1;grid.forEach((row,y)=>row.forEach((v,x)=>{if(v!==null){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}}));return {width:right<0?0:right-left+1,height:bottom<0?0:bottom-top+1};}
(()=>{
 let hoveredColour=null;
 const hoverDraw=draw;draw=function(){const result=hoverDraw.apply(this,arguments);if(hoveredColour!==null){const size=Number($('zoom').value);for(let y=0;y<state.height;y++)for(let x=0;x<state.width;x++){const v=state.grid[y][x],match=v!==null&&state.palette[v].hama===hoveredColour;if(!match){ctx.fillStyle='rgba(255,255,255,.72)';ctx.fillRect(x*size,y*size,size,size);}else if(size>=3){ctx.strokeStyle='#f2ad00';ctx.lineWidth=Math.min(2,size/3);ctx.strokeRect(x*size+1,y*size+1,Math.max(0,size-2),Math.max(0,size-2));}}}return result;};
 function hoverCode(target){const swatch=target.closest('.swatch');if(swatch&&$('palette').contains(swatch)){const index=Number(swatch.dataset.paletteIndex);return state.palette[index]?.hama||null;}const hama=target.closest('[data-hama]');return hama?hama.dataset.hama:null;}
 document.addEventListener('pointerover',e=>{const code=hoverCode(e.target);if(code!==hoveredColour){hoveredColour=code;draw();}});
 document.addEventListener('pointerout',e=>{if(hoveredColour!==null&&(!e.relatedTarget||hoverCode(e.relatedTarget)!==hoveredColour)){hoveredColour=null;draw();}});
 window.addEventListener('blur',()=>{if(hoveredColour!==null){hoveredColour=null;draw();}});
 $('zoom').min='0.5';$('zoom').step='0.5';$('referenceZoom').min='10';$('referenceZoom').step='5';
 fit=function(){const v=$('viewport');$('zoom').value=Math.max(.5,Math.min(40,Math.floor(Math.min((v.clientWidth-52)/state.width,(v.clientHeight-52)/state.height)*2)/2));draw();};
 $('fit').onclick=fit;
 const style=document.createElement('style');style.textContent='#referenceImage{min-width:0!important}';document.head.append(style);
 const removeUnused=document.createElement('button');removeUnused.id='removeUnusedColours';removeUnused.textContent='Remove unused colours';$('palette').before(removeUnused);
 removeUnused.onclick=()=>{const used=new Set(state.grid.flat().filter(v=>v!==null));if(!used.size){notice('The design is empty. Keep a colour available to start painting.');return;}const removed=state.palette.length-used.size;if(!removed){notice('Every colour is used in this design.');return;}snapshot();const mapping=new Map(),palette=[];state.palette.forEach((p,i)=>{if(used.has(i)){mapping.set(i,palette.length);palette.push(p);}});selected=mapping.get(selected)??0;state.grid=state.grid.map(row=>row.map(v=>v===null?null:mapping.get(v)));state.palette=palette;hoveredColour=null;refresh();notice('Removed '+removed+' unused colour'+(removed===1?'':'s')+'. Undo restores them.');};
 const previousPaletteUI=paletteUI;paletteUI=function(){const result=previousPaletteUI.apply(this,arguments);const buttons=Array.from($('palette').children);buttons.forEach((b,i)=>{b.dataset.paletteIndex=String(i);b.dataset.colourNumber=state.palette[i].hama;});buttons.sort((a,b)=>Number(a.dataset.colourNumber)-Number(b.dataset.colourNumber)).forEach(b=>$('palette').append(b));return result;};paletteUI();
 const canvasButton=document.createElement('button');canvasButton.id='resizeCanvas';canvasButton.textContent='Resize canvas';$('fit').after(canvasButton);
 const canvasDialog=document.createElement('dialog');canvasDialog.id='canvasSizeDialog';canvasDialog.className='resizeDialog';canvasDialog.innerHTML='<div class="modalhead"><h2>Resize canvas</h2><button id="canvasSizeCancel">Cancel</button></div><p>Add empty space or crop the edges. Beads keep their existing size and colours.</p><div class="resizeControls"><label class="field">Columns<input id="canvasSizeW" type="number" min="1" max="300"></label><label class="field">Rows<input id="canvasSizeH" type="number" min="1" max="300"></label><label class="field">Keep design at<select id="canvasAnchor"><option value="center">Centre</option><option value="top-left">Top left</option><option value="top">Top centre</option><option value="top-right">Top right</option><option value="left">Centre left</option><option value="right">Centre right</option><option value="bottom-left">Bottom left</option><option value="bottom">Bottom centre</option><option value="bottom-right">Bottom right</option></select></label></div><div class="resizePreviews"><section class="resizePreview"><h3>Canvas boundary over current design</h3><canvas id="canvasBoundaryPreview"></canvas><p class="resizeNote">Gold outline: new canvas. Red beads: would be cropped.</p></section><section class="resizePreview"><h3 id="canvasResultLabel">Result</h3><canvas id="canvasResultPreview"></canvas></section></div><p id="canvasSizeStatus" role="status"></p><label id="canvasCropConsentLabel" class="toggle" hidden><input id="canvasCropConsent" type="checkbox">Allow cropping these beads</label><div class="modalfooter"><button id="canvasSizeApply" class="primary">Resize canvas</button></div>';document.body.append(canvasDialog);
 let canvasSource=null,canvasPreview=null;
 function drawCanvasPreview(w,h,dx,dy,grid){const left=Math.min(0,dx),top=Math.min(0,dy),right=Math.max(w,dx+canvasSource.width),bottom=Math.max(h,dy+canvasSource.height),scale=Math.max(.5,Math.min(12,420/Math.max(right-left,bottom-top)));const c=$('canvasBoundaryPreview');c.width=Math.ceil((right-left)*scale)+8;c.height=Math.ceil((bottom-top)*scale)+8;const g=c.getContext('2d');g.fillStyle='#313846';g.fillRect(0,0,c.width,c.height);g.fillStyle='#e8edf2';g.fillRect(4-left*scale,4-top*scale,w*scale,h*scale);canvasSource.grid.forEach((row,y)=>row.forEach((v,x)=>{if(v===null)return;const nx=x+dx,ny=y+dy;g.fillStyle=nx<0||ny<0||nx>=w||ny>=h?'#ef4444':canvasSource.palette[v].color;g.fillRect(4+(nx-left)*scale,4+(ny-top)*scale,scale,scale);}));g.strokeStyle='#ffd166';g.lineWidth=2;g.strokeRect(4-left*scale,4-top*scale,w*scale,h*scale);const out=$('canvasResultPreview'),factor=Math.max(.5,Math.min(12,420/Math.max(w,h)));out.width=Math.ceil(w*factor);out.height=Math.ceil(h*factor);const og=out.getContext('2d');grid.forEach((row,y)=>row.forEach((v,x)=>{og.fillStyle=v===null?((x+y)%2?'#e8edf2':'#fff'):canvasSource.palette[v].color;og.fillRect(x*factor,y*factor,factor,factor);}));const size=Number($('editorBeadSize').value);$('canvasResultLabel').textContent=w+' × '+h+' canvas · ≈ '+(w*size/10).toFixed(1)+' × '+(h*size/10).toFixed(1)+' cm';}
 function canvasPreviewNow(){try{const w=Number($('canvasSizeW').value),h=Number($('canvasSizeH').value);if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>300||h>300)throw Error('Choose whole-number dimensions between 1 and 300.');const anchor=$('canvasAnchor').value;const dx=anchor.includes('left')?0:anchor.includes('right')?w-canvasSource.width:Math.floor((w-canvasSource.width)/2);const dy=anchor.includes('top')?0:anchor.includes('bottom')?h-canvasSource.height:Math.floor((h-canvasSource.height)/2);let removed=0;const grid=Array.from({length:h},()=>Array(w).fill(null));canvasSource.grid.forEach((row,y)=>row.forEach((v,x)=>{const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<w&&ny<h)grid[ny][nx]=v;else if(v!==null)removed++;}));canvasPreview={width:w,height:h,grid};drawCanvasPreview(w,h,dx,dy,grid);$('canvasCropConsentLabel').hidden=!removed;$('canvasSizeStatus').textContent=removed?removed.toLocaleString()+' beads fall outside the new canvas. Tick the box to allow cropping.':'All existing beads fit. New space will be empty.';$('canvasSizeApply').disabled=(w===canvasSource.width&&h===canvasSource.height)||(removed>0&&!$('canvasCropConsent').checked);}catch(e){canvasPreview=null;for(const id of ['canvasBoundaryPreview','canvasResultPreview']){$(id).width=1;$(id).height=1;}$('canvasSizeApply').disabled=true;$('canvasSizeStatus').textContent=e.message;}}
 canvasButton.onclick=()=>{canvasSource=clone(state);$('canvasSizeW').value=state.width;$('canvasSizeH').value=state.height;$('canvasAnchor').value='center';$('canvasCropConsent').checked=false;canvasDialog.showModal();canvasPreviewNow();};
 for(const id of ['canvasSizeW','canvasSizeH','canvasAnchor'])$(id).oninput=()=>{$('canvasCropConsent').checked=false;canvasPreviewNow();};$('canvasCropConsent').onchange=canvasPreviewNow;$('canvasSizeCancel').onclick=()=>canvasDialog.close();
 $('canvasSizeApply').onclick=()=>{if(!canvasPreview||$('canvasSizeApply').disabled)return;snapshot();state.width=canvasPreview.width;state.height=canvasPreview.height;state.grid=canvasPreview.grid;cursor={x:0,y:0};hoveredColour=null;refresh();fit();canvasDialog.close();notice('Canvas resized. Undo restores the previous canvas.');};
 const saveAsButton=document.createElement('button');saveAsButton.id='saveAsProject';saveAsButton.textContent='Save As…';$('saveLocal').after(saveAsButton);const duplicateButton=document.createElement('button');duplicateButton.id='duplicateProject';duplicateButton.textContent='Duplicate';saveAsButton.after(duplicateButton);
 const copyDialog=document.createElement('dialog');copyDialog.id='copyProjectDialog';copyDialog.innerHTML='<h2>Save project as</h2><label class="field">Project name<input id="copyProjectName" maxlength="160"></label><p>The original and the new copy will both be saved in Your projects.</p><p id="copyProjectError" role="status"></p><div class="modalfooter"><button id="copyProjectCancel">Cancel</button><button id="copyProjectApply" class="primary">Save new copy</button></div>';document.body.append(copyDialog);
 function uniqueCopyName(){const title=$('title').value.trim()||state.title||'Untitled pattern',names=new Set(Object.values(projects()).map(p=>p.title));let name=title+' copy',n=2;while(names.has(name))name=title+' copy '+n++;return name;}
 function saveProjectCopy(name){if(!name.trim())throw Error('Enter a project name.');const items=projects(),original=clone(state);original.title=$('title').value.trim()||original.title;original.projectId=original.projectId||crypto.randomUUID();const copy=clone(original);copy.title=name.trim();copy.projectId=crypto.randomUUID();items[original.projectId]=original;items[copy.projectId]=copy;localStorage.setItem(STORAGE+'-projects',JSON.stringify(items));snapshot();state=copy;hoveredColour=null;refresh();projectList();$('savedProjects').value=copy.projectId;notice('New copy saved. Your original is also in Your projects.');}
 saveAsButton.onclick=()=>{$('copyProjectName').value=uniqueCopyName();$('copyProjectError').textContent='';copyDialog.showModal();$('copyProjectName').focus();$('copyProjectName').select();};duplicateButton.onclick=()=>{try{saveProjectCopy(uniqueCopyName());}catch(e){notice('Could not save the copy: '+e.message,true);}};$('copyProjectCancel').onclick=()=>copyDialog.close();$('copyProjectApply').onclick=()=>{try{saveProjectCopy($('copyProjectName').value);copyDialog.close();}catch(e){$('copyProjectError').textContent='Could not save the copy: '+e.message;}};
 const eraser=document.querySelector('[data-tool="erase"]');eraser.textContent='Erase';eraser.title='Erase individual beads — click or drag (E)';eraser.classList.add('primary');eraser.onclick=()=>setTool('erase');document.querySelector('.toolbar').prepend(eraser);
 const button=document.createElement('button');button.id='newFromImage';button.textContent='New from image';$('newBtn').after(button);
 const blankButton=document.createElement('button');blankButton.textContent='Create from image';blankButton.onclick=()=>{$('newDialog').close();$('designImageFile').click();};$('newDialog').querySelector('.modalfooter').prepend(blankButton);
 const input=document.createElement('input');input.type='file';input.id='designImageFile';input.accept='image/png,image/jpeg,image/webp';input.hidden=true;document.body.append(input);button.onclick=()=>input.click();
 const previousReference=$('chooseReference').onclick;$('chooseReference').onclick=()=>{if(!state.grid.some(r=>r.some(v=>v!==null)))input.click();else previousReference();};
 const dialog=document.createElement('dialog');dialog.className='resizeDialog';dialog.id='imageDesignDialog';dialog.innerHTML='<div class="modalhead"><h2>Create design from image</h2><button id="imageDesignCancel">Cancel</button></div><p class="resizeNote">Choose your bead grid and preview the conversion. The image fits inside the grid using official Hama Midi colours. Fine details may need touching up.</p><div class="resizeControls"><label class="field">Columns<input id="imageDesignW" type="number" min="1" max="300" value="29"></label><label class="field">Rows<input id="imageDesignH" type="number" min="1" max="300" value="29"></label><label class="field">Bead size<select id="imageBeadSize"><option value="5">5 mm Midi</option><option value="2.6">2.6 mm Mini</option></select></label><label class="toggle"><input id="imageRemoveWhite" type="checkbox">Remove near-white background</label></div><label class="field">Colour smoothing: <output id="imageSmoothingValue">Off</output><input id="imageSmoothing" type="range" min="0" max="100" step="5" value="0"></label><p class="resizeNote">Increase smoothing to reduce speckled colours. Strong smoothing may remove small details. The preview updates as you adjust it.</p><p class="resizeNote">Transparent areas stay empty. White removal also removes white details inside the character; coloured backgrounds stay in the pattern.</p><div class="resizePresets"><button data-image-size="29">29 × 29</button><button data-image-size="45">45 × 45</button><button data-image-size="60">60 × 60</button><button data-image-size="90">90 × 90</button><button id="image60cm">≈60 cm</button></div><div class="resizePreviews"><section class="resizePreview"><h3>Select part of the template</h3><p class="resizeNote">Drag across the image to select an area, or use the whole image.</p><canvas id="imageDesignOriginal" style="display:block;max-width:100%;max-height:340px;width:auto;height:auto;margin:auto;touch-action:none;cursor:crosshair"></canvas><button id="imageCropReset">Use whole image</button><p id="imageCropStatus" class="resizeNote"></p></section><section class="resizePreview"><h3 id="imageDesignCount">Bead preview</h3><canvas id="imageDesignPreview"></canvas></section></div><p id="imageDesignMessage" role="status" class="resizeNote"></p><div class="modalfooter"><button id="imageReferenceOnly">Use as reference only</button><button id="imageDesignApply" class="primary">Create bead design</button></div>';document.body.append(dialog);
 try{$('imageBeadSize').value=localStorage.getItem('bead-studio-display-size')==='5'?'5':'2.6';}catch(e){}
 const sizeLabel=document.createElement('label');sizeLabel.className='toggle';sizeLabel.innerHTML='Bead size <select id="editorBeadSize"><option value="2.6">2.6 mm</option><option value="5">5 mm</option></select>';document.querySelector('.toolbar').append(sizeLabel);$('editorBeadSize').value=$('imageBeadSize').value;
 function changeBeadSize(value){const size=value==='5'?'5':'2.6';$('imageBeadSize').value=size;$('editorBeadSize').value=size;if($('resizeBeadSize'))$('resizeBeadSize').value=size;try{localStorage.setItem('bead-studio-display-size',size);}catch(e){}showDimensions();if(source)update();document.dispatchEvent(new Event('beadsizechange'));}
 $('editorBeadSize').onchange=()=>changeBeadSize($('editorBeadSize').value);
 document.addEventListener('beadsizeselect',e=>changeBeadSize(e.detail));
 const dimensions=document.createElement('span');dimensions.id='occupiedDimensions';$('toolInfo').after(dimensions);
 function showDimensions(){const b=beadOccupiedBounds(state.grid),size=Number($('imageBeadSize').value);dimensions.textContent='Design: ≈ '+(b.width*size/10).toFixed(1)+' × '+(b.height*size/10).toFixed(1)+' cm / ≈ '+(b.width*size/25.4).toFixed(1)+' × '+(b.height*size/25.4).toFixed(1)+' in ('+size+' mm beads)';}
 const previousDraw=draw;draw=function(){const result=previousDraw.apply(this,arguments);showDimensions();return result;};showDimensions();
 let source=null,reference=null,preview=null,name='New design',crop=null,drag=null;
 const cropCanvas=$('imageDesignOriginal');
 function drawCrop(){if(!source)return;const ratio=Math.min(1,600/source.width,340/source.height);cropCanvas.width=Math.max(1,Math.round(source.width*ratio));cropCanvas.height=Math.max(1,Math.round(source.height*ratio));const g=cropCanvas.getContext('2d');g.drawImage(source,0,0,cropCanvas.width,cropCanvas.height);if(crop){const sx=cropCanvas.width/source.width,sy=cropCanvas.height/source.height,x=crop.x*sx,y=crop.y*sy,w=crop.width*sx,h=crop.height*sy;g.fillStyle='rgba(0,0,0,.45)';g.fillRect(0,0,cropCanvas.width,y);g.fillRect(0,y+h,cropCanvas.width,cropCanvas.height-y-h);g.fillRect(0,y,x,h);g.fillRect(x+w,y,cropCanvas.width-x-w,h);g.strokeStyle='#ffd166';g.lineWidth=2;g.strokeRect(x,y,w,h);} $('imageCropStatus').textContent=crop?'Selected area: '+crop.width+' × '+crop.height+' image pixels':'Whole image selected';}
 function cropPoint(e){const r=cropCanvas.getBoundingClientRect();return {x:Math.max(0,Math.min(source.width,(e.clientX-r.left)/r.width*source.width)),y:Math.max(0,Math.min(source.height,(e.clientY-r.top)/r.height*source.height))};}
 cropCanvas.onpointerdown=e=>{if(!source||e.button!==0)return;e.preventDefault();drag={start:cropPoint(e),previous:crop,id:e.pointerId};cropCanvas.setPointerCapture(e.pointerId);};
 cropCanvas.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const p=cropPoint(e),a=drag.start;crop={x:Math.min(source.width-1,Math.floor(Math.min(a.x,p.x))),y:Math.min(source.height-1,Math.floor(Math.min(a.y,p.y))),width:Math.max(1,Math.ceil(Math.abs(p.x-a.x))),height:Math.max(1,Math.ceil(Math.abs(p.y-a.y)))};crop.width=Math.min(crop.width,source.width-crop.x);crop.height=Math.min(crop.height,source.height-crop.y);drawCrop();};
 cropCanvas.onpointerup=e=>{if(!drag||drag.id!==e.pointerId)return;const p=cropPoint(e);if(Math.abs(p.x-drag.start.x)<1||Math.abs(p.y-drag.start.y)<1)crop=drag.previous;drag=null;drawCrop();update();};
 cropCanvas.onpointercancel=()=>{if(drag){crop=drag.previous;drag=null;drawCrop();update();}};
 $('imageCropReset').onclick=()=>{crop=null;drag=null;drawCrop();update();};
 function resetCrop(){$('imageSmoothing').value=0;$('imageSmoothingValue').textContent='Off';crop=null;drag=null;drawCrop();}
 function selectedReference(){if(!crop)return reference;const c=document.createElement('canvas');c.width=crop.width;c.height=crop.height;c.getContext('2d').drawImage(source,crop.x,crop.y,crop.width,crop.height,0,0,c.width,c.height);return c.toDataURL('image/png');}

 const generate=document.createElement('button');generate.id='generateFromTemplate';generate.textContent='Generate from template';$('chooseReference').after(generate);generate.onclick=async()=>{if(!state.reference){notice('Choose a reference image first.',true);return;}try{source=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Could not open the reference image.'));img.src=state.reference;});reference=state.reference;name=state.title+' generated';resetCrop();$('imageDesignW').value=state.width;$('imageDesignH').value=state.height;$('imageRemoveWhite').checked=false;dialog.showModal();update();}catch(e){notice(e.message,true);}};

 function update(){try{preview=beadPatternFromImage(source,Number($('imageDesignW').value),Number($('imageDesignH').value),$('imageRemoveWhite').checked,crop,Number($('imageSmoothing').value));const c=$('imageDesignPreview'),scale=Math.max(1,Math.min(12,Math.floor(420/Math.max(preview.width,preview.height))));c.width=preview.width*scale;c.height=preview.height*scale;const g=c.getContext('2d');const bounds=beadOccupiedBounds(preview.grid);let beads=0;preview.grid.forEach((row,y)=>row.forEach((v,x)=>{g.fillStyle=v===null?((x+y)%2?'#e5e9ee':'#fff'):preview.palette[v].color;g.fillRect(x*scale,y*scale,scale,scale);if(v!==null)beads++;}));$('imageDesignCount').textContent=preview.width+' × '+preview.height+' · ≈ '+(bounds.width*Number($('imageBeadSize').value)/10).toFixed(1)+' × '+(bounds.height*Number($('imageBeadSize').value)/10).toFixed(1)+' cm / ≈ '+(bounds.width*Number($('imageBeadSize').value)/25.4).toFixed(1)+' × '+(bounds.height*Number($('imageBeadSize').value)/25.4).toFixed(1)+' in design · '+beads.toLocaleString('en-GB')+' beads · '+preview.palette.length+' colours';$('imageDesignMessage').textContent='Create the design to start editing. Your existing pattern will be saved in Your projects.';$('imageDesignApply').disabled=false;}catch(e){preview=null;$('imageDesignMessage').textContent=e.message;$('imageDesignApply').disabled=true;}}
 input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>25*1024*1024){notice('Please choose an image under 25 MB.',true);input.value='';return;}const u=URL.createObjectURL(f);try{source=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Could not open that image.'));img.src=u;});if(source.width*source.height>30000000)throw Error('Please choose an image under 30 megapixels.');reference=imageReference(source);resetCrop();name=f.name.replace(/\.[^.]+$/,'');const blank=!state.grid.some(r=>r.some(v=>v!==null));$('imageDesignW').value=blank?state.width:29;$('imageDesignH').value=blank?state.height:29;$('imageRemoveWhite').checked=false;dialog.showModal();update();}catch(e){notice(e.message,true);}finally{URL.revokeObjectURL(u);input.value='';}};
 $('image60cm').onclick=()=>{const size=Math.round(600/Number($('imageBeadSize').value));$('imageDesignW').value=size;$('imageDesignH').value=size;update();};
 $('imageBeadSize').onchange=()=>changeBeadSize($('imageBeadSize').value);
 $('imageSmoothing').oninput=()=>{$('imageSmoothingValue').textContent=$('imageSmoothing').value==='0'?'Off':$('imageSmoothing').value+'%';update();};
 for(const id of ['imageDesignW','imageDesignH'])$(id).oninput=update;$('imageRemoveWhite').onchange=update;dialog.querySelectorAll('[data-image-size]').forEach(b=>b.onclick=()=>{$('imageDesignW').value=b.dataset.imageSize;$('imageDesignH').value=b.dataset.imageSize;update();});$('imageDesignCancel').onclick=()=>dialog.close();
 $('imageReferenceOnly').onclick=()=>{snapshot();state.reference=reference;refresh();dialog.close();notice('Reference image updated.');};
 $('imageDesignApply').onclick=()=>{if(!preview)return;try{if(state.grid.some(r=>r.some(v=>v!==null))){const saved=projects(),original=clone(state);original.projectId=original.projectId||crypto.randomUUID();saved[original.projectId]=original;localStorage.setItem(STORAGE+'-projects',JSON.stringify(saved));}load({...preview,title:name,reference:selectedReference(),projectId:crypto.randomUUID()});projectList();dialog.close();notice('Bead design created from your image. You can now paint, erase or resize it.');}catch(e){$('imageDesignMessage').textContent=e.message;}};
 document.querySelector('.brand .sub').textContent='Version 24 · Save As & Duplicate';
})();
