'use strict';
function beadPatternFromImage(img,width,height,removeWhite=false){
 if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>150||height>150)throw Error('Choose dimensions between 1 and 150.');
 const c=document.createElement('canvas');c.width=width;c.height=height;const g=c.getContext('2d',{willReadFrequently:true});g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';const scale=Math.min(width/img.width,height/img.height),w=img.width*scale,h=img.height*scale;g.drawImage(img,(width-w)/2,(height-h)/2,w,h);const data=g.getImageData(0,0,width,height).data,palette=[],indices=new Map();
 const grid=Array.from({length:height},(_,y)=>Array.from({length:width},(_,x)=>{const i=(y*width+x)*4;if(data[i+3]<128||(removeWhite&&data[i]>242&&data[i+1]>242&&data[i+2]>242))return null;const colour=nearestHama(hex(data[i],data[i+1],data[i+2]));if(!indices.has(colour.hama)){const index=palette.length;indices.set(colour.hama,index);palette.push({hama:colour.hama,name:colour.name,color:colour.color,code:index<26?String.fromCharCode(65+index):'C'+(index+1)});}return indices.get(colour.hama);}));
 if(!palette.length)throw Error('No visible beads found. Try disabling “Remove near-white background”.');return {width,height,palette,grid};
}
(()=>{
 const button=document.createElement('button');button.id='newFromImage';button.textContent='New from image';$('newBtn').after(button);
 const blankButton=document.createElement('button');blankButton.textContent='Create from image';blankButton.onclick=()=>{$('newDialog').close();$('designImageFile').click();};$('newDialog').querySelector('.modalfooter').prepend(blankButton);
 const input=document.createElement('input');input.type='file';input.id='designImageFile';input.accept='image/png,image/jpeg,image/webp';input.hidden=true;document.body.append(input);button.onclick=()=>input.click();
 const previousReference=$('chooseReference').onclick;$('chooseReference').onclick=()=>{if(!state.grid.some(r=>r.some(v=>v!==null)))input.click();else previousReference();};
 const dialog=document.createElement('dialog');dialog.className='resizeDialog';dialog.id='imageDesignDialog';dialog.innerHTML='<div class="modalhead"><h2>Create design from image</h2><button id="imageDesignCancel">Cancel</button></div><p class="resizeNote">Choose your bead grid and preview the conversion. The image fits inside the grid using official Hama Midi colours. Fine details may need touching up.</p><div class="resizeControls"><label class="field">Columns<input id="imageDesignW" type="number" min="1" max="150" value="29"></label><label class="field">Rows<input id="imageDesignH" type="number" min="1" max="150" value="29"></label><label class="toggle"><input id="imageRemoveWhite" type="checkbox">Remove near-white background</label></div><p class="resizeNote">Transparent areas stay empty. White removal also removes white details inside the character; coloured backgrounds stay in the pattern.</p><div class="resizePresets"><button data-image-size="29">29 × 29</button><button data-image-size="45">45 × 45</button><button data-image-size="60">60 × 60</button><button data-image-size="90">90 × 90</button></div><div class="resizePreviews"><section class="resizePreview"><h3>Original image</h3><img id="imageDesignOriginal" alt="Uploaded reference" style="display:block;max-width:100%;max-height:340px;margin:auto"></section><section class="resizePreview"><h3 id="imageDesignCount">Bead preview</h3><canvas id="imageDesignPreview"></canvas></section></div><p id="imageDesignMessage" role="status" class="resizeNote"></p><div class="modalfooter"><button id="imageReferenceOnly">Use as reference only</button><button id="imageDesignApply" class="primary">Create bead design</button></div>';document.body.append(dialog);
 let source=null,reference=null,preview=null,name='New design';
 const generate=document.createElement('button');generate.id='generateFromTemplate';generate.textContent='Generate from template';$('chooseReference').after(generate);generate.onclick=async()=>{if(!state.reference){notice('Choose a reference image first.',true);return;}try{source=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Could not open the reference image.'));img.src=state.reference;});reference=state.reference;name=state.title+' generated';$('imageDesignOriginal').src=reference;$('imageDesignW').value=state.width;$('imageDesignH').value=state.height;$('imageRemoveWhite').checked=false;dialog.showModal();update();}catch(e){notice(e.message,true);}};

 function update(){try{preview=beadPatternFromImage(source,Number($('imageDesignW').value),Number($('imageDesignH').value),$('imageRemoveWhite').checked);const c=$('imageDesignPreview'),scale=Math.max(1,Math.min(12,Math.floor(420/Math.max(preview.width,preview.height))));c.width=preview.width*scale;c.height=preview.height*scale;const g=c.getContext('2d');let beads=0;preview.grid.forEach((row,y)=>row.forEach((v,x)=>{g.fillStyle=v===null?((x+y)%2?'#e5e9ee':'#fff'):preview.palette[v].color;g.fillRect(x*scale,y*scale,scale,scale);if(v!==null)beads++;}));$('imageDesignCount').textContent=preview.width+' × '+preview.height+' · '+beads+' beads · '+preview.palette.length+' colours';$('imageDesignMessage').textContent='Create the design to start editing. Your existing pattern will be saved in Your projects.';$('imageDesignApply').disabled=false;}catch(e){preview=null;$('imageDesignMessage').textContent=e.message;$('imageDesignApply').disabled=true;}}
 input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>25*1024*1024){notice('Please choose an image under 25 MB.',true);input.value='';return;}const u=URL.createObjectURL(f);try{source=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Could not open that image.'));img.src=u;});if(source.width*source.height>30000000)throw Error('Please choose an image under 30 megapixels.');reference=imageReference(source);$('imageDesignOriginal').src=reference;name=f.name.replace(/\.[^.]+$/,'');const blank=!state.grid.some(r=>r.some(v=>v!==null));$('imageDesignW').value=blank?state.width:29;$('imageDesignH').value=blank?state.height:29;$('imageRemoveWhite').checked=false;dialog.showModal();update();}catch(e){notice(e.message,true);}finally{URL.revokeObjectURL(u);input.value='';}};
 for(const id of ['imageDesignW','imageDesignH'])$(id).oninput=update;$('imageRemoveWhite').onchange=update;dialog.querySelectorAll('[data-image-size]').forEach(b=>b.onclick=()=>{$('imageDesignW').value=b.dataset.imageSize;$('imageDesignH').value=b.dataset.imageSize;update();});$('imageDesignCancel').onclick=()=>dialog.close();
 $('imageReferenceOnly').onclick=()=>{snapshot();state.reference=reference;refresh();dialog.close();notice('Reference image updated.');};
 $('imageDesignApply').onclick=()=>{if(!preview)return;try{if(state.grid.some(r=>r.some(v=>v!==null))){const saved=projects(),original=clone(state);original.projectId=original.projectId||crypto.randomUUID();saved[original.projectId]=original;localStorage.setItem(STORAGE+'-projects',JSON.stringify(saved));}load({...preview,title:name,reference,projectId:crypto.randomUUID()});projectList();dialog.close();notice('Bead design created from your image. You can now paint, erase or resize it.');}catch(e){$('imageDesignMessage').textContent=e.message;}};
 document.querySelector('.brand .sub').textContent='Version 11 · Create designs from images';
})();
