'use strict';
const BeadStock = (() => {
  const integer = (n, min = 0) => { if (!Number.isSafeInteger(n) || n < min || n > 100000000) throw Error('Enter a whole number between '+min+' and 100,000,000.'); return n; };
  function requirements(project, copies=1) {
    integer(copies,1);const used={};
    for(const row of project.grid)for(const v of row)if(v!==null){const id=project.palette[v].hama;if(!id)throw Error('Every bead must have a Hama colour number.');used[id]=(used[id]||0)+copies;integer(used[id]);}
    return used;
  }
  function quote(db,need){return Object.entries(need).map(([id,needed])=>({id,needed,owned:db.stock[id]||0,remaining:(db.stock[id]||0)-needed}));}
  function finalise(db,order){
    if(db.orders.some(o=>o.projectId===order.projectId&&!o.cancelled))throw Error('This project has already been finalised. Start another customer copy to deduct again.');
    if(!order.customer.trim())throw Error('Enter a customer name or order reference.');
    if(!Object.keys(order.need).length)throw Error('This pattern has no beads.');
    const rows=quote(db,order.need);if(rows.some(r=>r.remaining<0))throw Error('Not enough stock. Add the missing beads before finalising.');
    const next=JSON.parse(JSON.stringify(db));for(const r of rows)next.stock[r.id]=r.remaining;
    next.orders.push(order);return next;
  }
  function cancel(db,id){const next=JSON.parse(JSON.stringify(db)),o=next.orders.find(o=>o.id===id);if(!o||o.cancelled)throw Error('This order has already been cancelled.');for(const [id,n] of Object.entries(o.need))next.stock[id]=integer((next.stock[id]||0)+n);o.cancelled=new Date().toISOString();return next;}
  return {integer,requirements,quote,finalise,cancel};
})();
// User interface and persistent, atomic stock transactions.
(() => {
 const KEY='bead-studio-stock-v1',byId=new Map(HAMA.map(h=>[h.hama,h]));
 const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const style=el('style');style.textContent=`.stockdialog{width:min(94vw,850px)}.stockscroll{max-height:48vh;overflow:auto;margin:14px 0}.stocktable{width:100%;border-collapse:collapse;font-size:13px}.stocktable th,.stocktable td{padding:9px 7px;border-bottom:1px solid var(--line);text-align:right}.stocktable th:first-child,.stocktable td:first-child{text-align:left}.stockchip{display:inline-block;width:22px;height:22px;border:1px solid #ffffff55;border-radius:4px;vertical-align:middle;margin-right:9px}.stockshort{color:#ffb1ad}.stockzero{color:#ffd185}.stockok{color:#99dfbd}.stocktable input{width:95px}.stockmessage{min-height:20px;margin-top:10px}.stockorders{border-top:1px solid var(--line);margin-top:20px;padding-top:14px}.stockorder{padding:12px 0;border-bottom:1px solid var(--line)}.stockcontrols{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.stockcontrols input{max-width:260px}.stockhint{font-size:12px;color:var(--muted);line-height:1.5}`;document.head.append(style);
 function read(){const raw=localStorage.getItem(KEY);if(!raw)return {version:1,stock:{},orders:[],purchases:[]};return validate(JSON.parse(raw));}
 function validate(d){if(!d||d.version!==1||!d.stock||!Array.isArray(d.orders)||!Array.isArray(d.purchases))throw Error('Invalid inventory backup.');for(const [id,n]of Object.entries(d.stock)){if(!byId.has(id))throw Error('Unknown Hama colour '+id);BeadStock.integer(n);}const ids=new Set();for(const o of d.orders){if(!o||typeof o.id!=='string'||ids.has(o.id)||typeof o.projectId!=='string'||typeof o.customer!=='string'||typeof o.title!=='string'||!o.need)throw Error('Invalid order record.');ids.add(o.id);for(const [id,n]of Object.entries(o.need)){if(!byId.has(id))throw Error('Unknown Hama colour.');BeadStock.integer(n,1);}}return d;}
 function message(text,error=false){notice(text,error);for(const e of document.querySelectorAll('.stockmessage')){e.textContent=text;e.classList.toggle('stockshort',error);}}
 async function transaction(fn){try{const work=()=>{const next=fn(read());validate(next);localStorage.setItem(KEY,JSON.stringify(next));};if(navigator.locks)await navigator.locks.request(KEY,work);else work();render();return true;}catch(e){message(e.message+' Stock was not changed.',true);return false;}}
 const panel=el('section');panel.className='panel';panel.innerHTML='<h2>Stock & customer orders</h2><div id="stockSummary" class="stockhint"></div><button id="inventoryOpen" class="wide">Manage inventory</button><button id="orderOpen" class="wide primary">Finalise for customer</button><button id="orderCopy" class="wide small" hidden>Start another customer copy</button><p class="help">Editing and saving do not use stock. Finalising deducts beads once.</p>';document.querySelector('aside').prepend(panel);
 const inventory=el('dialog');inventory.className='stockdialog';inventory.innerHTML='<div class="modalhead"><h2>Bead inventory</h2><button id="inventoryClose">Close</button></div><p class="stockhint">Enter your starting stock with Set total. Use Add purchase when you buy more beads. Counts are shared across your projects in this browser.</p><div class="stockcontrols"><label class="field">Find Hama number<input id="stockSearch" placeholder="e.g. 18" type="search"></label><button id="stockExport">Back up inventory</button><button id="stockImport">Restore backup</button><input id="stockFile" type="file" accept=".json" hidden></div><div class="stockscroll"><table class="stocktable"><thead><tr><th>Hama colour</th><th>In stock</th><th>Quantity</th><th>Action</th></tr></thead><tbody id="stockRows"></tbody></table></div><div class="stockmessage" role="status"></div><section class="stockorders"><h2>Finalised customer projects</h2><div id="stockOrders"></div></section>';document.body.append(inventory);
 const order=el('dialog');order.className='stockdialog';order.innerHTML='<div class="modalhead"><h2>Finalise for customer</h2><button id="orderClose">Close</button></div><p id="orderTitle"></p><div class="stockcontrols"><label class="field">Customer / order reference<input id="orderCustomer" maxlength="150" placeholder="e.g. Emma / order 104"></label><label class="field">Copies<input id="orderCopies" type="number" min="1" max="10000" value="1"></label></div><div class="stockscroll"><table class="stocktable"><thead><tr><th>Hama colour</th><th>Needed</th><th>In stock</th><th>After order</th></tr></thead><tbody id="orderRows"></tbody></table></div><p id="orderWarning" role="status"></p><div class="stockmessage" role="status"></div><div class="modalfooter"><button id="orderConfirm" class="primary">Finalise & deduct stock</button></div><p class="stockhint">This records an order and deducts the listed beads. Shortages must be restocked first. Undo in the editor does not reverse a stock deduction; cancel the order in Inventory to return the beads.</p>';document.body.append(order);
 function colourCell(id){const td=el('td'),h=byId.get(id),chip=el('span');chip.className='stockchip';chip.style.background=h.color;td.append(chip,el('span',h.name));return td;}
 function copies(){const n=Number($('orderCopies').value);BeadStock.integer(n,1);if(n>10000)throw Error('Use 1–10,000 copies.');return n;}
 function currentOrder(db){return state.projectId&&db.orders.find(o=>o.projectId===state.projectId&&!o.cancelled);}
 function renderSummary(db){const previous=currentOrder(db),rows=BeadStock.quote(db,BeadStock.requirements(state)),short=rows.filter(r=>r.remaining<0),zero=rows.filter(r=>r.remaining===0);$('stockSummary').textContent=previous?'Finalised for '+previous.customer+'. Stock already deducted.':!rows.length?'Add beads to check stock.':short.length?short.length+' colours short for one copy: '+short.map(r=>r.id+' (need '+(-r.remaining)+' more)').join(', '):zero.length?'Enough for one copy. Will use up Hama '+zero.map(r=>r.id).join(', ')+'.':'Enough stock for one copy.';$('stockSummary').classList.toggle('stockshort',!previous&&short.length>0);$('orderCopy').hidden=!previous;$('orderOpen').disabled=!!previous||!rows.length;}
 function renderInventory(db){$('stockRows').replaceChildren();const search=$('stockSearch').value.trim();for(const h of HAMA){if(search&&!h.name.toLowerCase().includes(search.toLowerCase()))continue;const tr=el('tr');tr.append(colourCell(h.hama),el('td',String(db.stock[h.hama]||0)));const input=el('input');input.type='number';input.min='0';input.step='1';input.placeholder='0';input.setAttribute('aria-label','Quantity for '+h.name);const td=el('td');td.append(input);tr.append(td);const actions=el('td'),add=el('button','Add purchase'),set=el('button','Set total');add.className=set.className='small';async function adjust(mode){try{if(input.value==='')throw Error('Enter a quantity first.');const value=BeadStock.integer(Number(input.value),mode==='add'?1:0);if(mode==='set'&&!confirm('Set '+h.name+' stock to '+value+' beads?'))return;const ok=await transaction(db=>{db.stock[h.hama]=BeadStock.integer(mode==='add'?(db.stock[h.hama]||0)+value:value);db.purchases.push({id:crypto.randomUUID(),hama:h.hama,mode,quantity:value,date:new Date().toISOString()});return db;});if(ok)message(mode==='add'?'Purchase added.':'Stock total updated.');}catch(e){message(e.message,true);}}add.onclick=()=>adjust('add');set.onclick=()=>adjust('set');actions.append(add,set);tr.append(actions);$('stockRows').append(tr);}
 $('stockOrders').replaceChildren();if(!db.orders.length)$('stockOrders').textContent='No customer orders finalised yet.';for(const o of [...db.orders].reverse()){const box=el('div');box.className='stockorder';box.append(el('strong',o.title+' — '+o.customer),el('p',o.copies+' copies · '+new Date(o.date).toLocaleString()+(o.cancelled?' · Cancelled; beads returned':'')),el('p',Object.entries(o.need).map(([id,n])=>'Hama '+id+': '+n).join(' · ')));if(!o.cancelled){const cancel=el('button','Cancel order & return beads');cancel.className='small';cancel.onclick=async()=>{if(!confirm('Cancel this order and return its beads to inventory?'))return;if(await transaction(db=>BeadStock.cancel(db,o.id)))message('Order cancelled. Beads returned to inventory.');};box.append(cancel);}$('stockOrders').append(box);}}
 function renderOrder(db){$('orderTitle').textContent=state.title;$('orderRows').replaceChildren();try{const rows=BeadStock.quote(db,BeadStock.requirements(state,copies())),short=rows.filter(r=>r.remaining<0),zero=rows.filter(r=>r.remaining===0);for(const r of rows){const tr=el('tr');tr.className=r.remaining<0?'stockshort':r.remaining===0?'stockzero':'';tr.append(colourCell(r.id),el('td',r.needed),el('td',r.owned),el('td',r.remaining<0?'Short '+(-r.remaining):r.remaining===0?'0 — runs out':r.remaining));$('orderRows').append(tr);}const done=currentOrder(db);$('orderWarning').textContent=done?'Already finalised for '+done.customer+'.':short.length?'Cannot finalise: restock Hama '+short.map(r=>r.id+' (+'+(-r.remaining)+')').join(', ')+'.':zero.length?'Warning: this order will use up Hama '+zero.map(r=>r.id).join(', ')+'.':'Enough stock for this order.';$('orderWarning').className=short.length?'stockshort':zero.length?'stockzero':'stockok';$('orderConfirm').disabled=!!done||!rows.length||!!short.length||!$('orderCustomer').value.trim();}catch(e){$('orderWarning').textContent=e.message;$('orderConfirm').disabled=true;}}
 function render(){try{const db=read();renderSummary(db);if(inventory.open)renderInventory(db);if(order.open)renderOrder(db);}catch(e){message('Inventory could not be read: '+e.message,true);$('orderOpen').disabled=true;$('orderConfirm').disabled=true;}}
 $('inventoryOpen').onclick=()=>{inventory.showModal();render();};$('inventoryClose').onclick=()=>inventory.close();$('orderOpen').onclick=()=>{order.showModal();render();};$('orderClose').onclick=()=>order.close();$('stockSearch').oninput=()=>render();$('orderCopies').oninput=()=>render();$('orderCustomer').oninput=()=>render();
 $('orderConfirm').onclick=async()=>{try{const quantity=copies(),customer=$('orderCustomer').value.trim();state.projectId=state.projectId||crypto.randomUUID();state.title=$('title').value.trim()||state.title;if(!persist())throw Error('Project could not be saved. Export a backup and free browser storage first.');const pending={id:crypto.randomUUID(),projectId:state.projectId,title:state.title,customer,copies:quantity,need:BeadStock.requirements(state,quantity),date:new Date().toISOString(),cancelled:null};$('orderConfirm').disabled=true;if(await transaction(db=>BeadStock.finalise(db,pending))){message('Customer project finalised. Beads deducted once.');order.close();}}catch(e){message(e.message,true);}};
 $('orderCopy').onclick=()=>{if(!confirm('Start a new customer copy of this design? Its beads will only be deducted when you finalise it.'))return;state.projectId=crypto.randomUUID();persist();$('orderCustomer').value='';$('orderCopies').value=1;render();notice('New customer copy started.');};
 $('stockExport').onclick=()=>{try{download(new Blob([JSON.stringify(read(),null,2)],{type:'application/json'}),'bead-inventory-backup.json');}catch(e){message(e.message,true);}};
 $('stockImport').onclick=()=>$('stockFile').click();$('stockFile').onchange=async()=>{try{const f=$('stockFile').files[0];if(!f)return;if(f.size>10000000)throw Error('Backup is too large.');const db=validate(JSON.parse(await f.text()));if(!confirm('Replace current inventory and order history with this backup?'))return;if(await transaction(()=>db))message('Inventory restored.');}catch(e){message(e.message,true);}finally{$('stockFile').value='';}};
 const originalRefresh=refresh;refresh=function(){originalRefresh();render();};window.addEventListener('storage',e=>{if(e.key===KEY)render();});document.querySelector('.brand .sub').textContent='Version 9 · Inventory & customer orders';render();
})();
