'use strict';
const BeadResize = (() => {
 function resize(source,width,height,mode='simplify'){
  if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>300||height>300)throw Error('Choose whole-number dimensions between 1 and 300.');
  const sx=source.width/width,sy=source.height/height;
  const grid=Array.from({length:height},(_,y)=>Array.from({length:width},(_,x)=>{
   const cx=Math.min(source.width-1,Math.floor((x+.5)*sx)),cy=Math.min(source.height-1,Math.floor((y+.5)*sy)),centre=source.grid[cy][cx];
   if(mode==='nearest'||(width>=source.width&&height>=source.height))return centre;
   const weights=new Map();const left=x*sx,right=(x+1)*sx,top=y*sy,bottom=(y+1)*sy;
   for(let yy=Math.floor(top);yy<Math.min(source.height,Math.ceil(bottom));yy++)for(let xx=Math.floor(left);xx<Math.min(source.width,Math.ceil(right));xx++){
    const area=(Math.min(right,xx+1)-Math.max(left,xx))*(Math.min(bottom,yy+1)-Math.max(top,yy));const colour=source.grid[yy][xx];weights.set(colour,(weights.get(colour)||0)+area);
   }
   let best=centre,weight=weights.get(centre)||0;for(const [colour,amount]of weights)if(amount>weight+1e-9){best=colour;weight=amount;}return best;
  }));return {...source,width,height,grid};
 }
 return {resize};
})();
(() => {
 const button=document.createElement('button');button.id='resizeDesign';button.textContent='Resize design';button.title='Try a smaller or larger bead grid';$('fit').after(button);
 const style=document.createElement('style');style.textContent='.resizeDialog{width:min(96vw,1000px)}.resizePreviews{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:18px 0}.resizePreview{min-width:0;padding:12px;background:#111720;border-radius:10px}.resizePreview h3{font-size:13px;margin:0 0 10px}.resizePreview canvas{display:block;max-width:100%;max-height:340px;width:auto;height:auto;margin:auto;image-rendering:pixelated}.resizeControls{display:flex;align-items:end;gap:12px;flex-wrap:wrap}.resizeControls input[type=number]{width:95px}.resizeControls select{max-width:260px}.resizePresets{display:flex;gap:7px;flex-wrap:wrap;margin:14px 0}.resizeNote{color:var(--muted);font-size:12px;line-height:1.6}.resizeWarning{color:#ffd185}@media(max-width:540px){.resizePreviews{gap:6px}.resizePreview{padding:6px}.resizePreview canvas{max-height:230px}}';document.head.append(style);
 const dialog=document.createElement('dialog');dialog.id='resizeDialog';dialog.className='resizeDialog';dialog.innerHTML='<div class="modalhead"><h2>Resize your design</h2><button id="resizeCancel">Cancel</button></div><p class="resizeNote">Try different sizes and compare the result. Smaller grids simplify fine details; larger grids enlarge the existing design. Both methods keep your Hama colours.</p><div class="resizeControls"><label class="field">Columns<input id="resizeW" type="number" min="1" max="300"></label><label class="field">Rows<input id="resizeH" type="number" min="1" max="300"></label><label class="toggle"><input id="resizeRatio" type="checkbox" checked>Keep proportions</label><label class="field">Bead size<select id="resizeBeadSize"><option value="2.6">2.6 mm</option><option value="5">5 mm</option></select></label><label class="field">Method<select id="resizeMethod"><option value="simplify">Simplify shapes</option><option value="nearest">Keep pixel edges</option></select></label></div><div class="resizePresets"><span class="resizeNote">Longest side:</span><button data-resize="29">29 beads</button><button data-resize="45">45 beads</button><button data-resize="60">60 beads</button><button data-resize="90">90 beads</button><button id="resize60cm">≈60 cm</button><button data-resize="300">300 beads</button><button id="resizeHalf">Half size</button><button id="resizeDouble">Double size</button></div><div class="resizePreviews"><section class="resizePreview"><h3 id="resizeOriginalLabel"></h3><canvas id="resizeOriginal" aria-label="Original pixel design"></canvas></section><section class="resizePreview"><h3 id="resizeResultLabel"></h3><canvas id="resizeResult" aria-label="Resized pixel design preview"></canvas></section></div><p id="resizeMessage" role="status" class="resizeNote"></p><div class="modalfooter"><button id="resizeApply" class="primary">Create resized copy</button></div><p class="resizeNote">Your original is saved in Your projects. The copy can be edited and finalised separately. Stock is deducted only when you finalise a customer order. Undo returns to the original.</p>';document.body.append(dialog);
 let source=null,preview=null;
 function count(d){return d.grid.reduce((n,row)=>n+row.filter(v=>v!==null).length,0);}
 function paint(canvas,d){const scale=Math.max(1,Math.min(12,Math.floor(420/Math.max(d.width,d.height))));canvas.width=d.width*scale;canvas.height=d.height*scale;const g=canvas.getContext('2d');d.grid.forEach((row,y)=>row.forEach((v,x)=>{g.fillStyle=v===null?((x+y)%2?'#e5e9ee':'#fff'):d.palette[v].color;g.fillRect(x*scale,y*scale,scale,scale);}));}
 function centimetres(project){const b=beadOccupiedBounds(project.grid),size=Number($('resizeBeadSize').value);return ' · ≈ '+(b.width*size/10).toFixed(1)+' × '+(b.height*size/10).toFixed(1)+' cm design';}
 $('resizeBeadSize').onchange=()=>document.dispatchEvent(new CustomEvent('beadsizeselect',{detail:$('resizeBeadSize').value}));
 document.addEventListener('beadsizechange',()=>{if(source&&dialog.open){$('resizeOriginalLabel').textContent='Original '+source.width+' × '+source.height+centimetres(source)+' · '+count(source).toLocaleString()+' beads';previewNow();}});
 function previewNow(){try{const w=Number($('resizeW').value),h=Number($('resizeH').value);preview=BeadResize.resize(source,w,h,$('resizeMethod').value);paint($('resizeResult'),preview);$('resizeResultLabel').textContent=w+' × '+h+centimetres(preview)+' · '+count(preview).toLocaleString()+' beads';const same=w===source.width&&h===source.height;$('resizeApply').disabled=same;$('resizeMessage').textContent=same?'Choose a different size to create a copy.':w<source.width||h<source.height?'Check eyes, outlines and other small details in the preview. You can touch these up after resizing.':'Larger pixels preserve the current shapes; no new details are invented.';$('resizeMessage').className='resizeNote';}catch(e){preview=null;$('resizeApply').disabled=true;$('resizeMessage').textContent=e.message;$('resizeMessage').className='resizeWarning';}}
 function dimensionsFromWidth(){if($('resizeRatio').checked){const n=Number($('resizeW').value);if(n>=1&&n<=300)$('resizeH').value=Math.max(1,Math.round(n*source.height/source.width));}previewNow();}
 function dimensionsFromHeight(){if($('resizeRatio').checked){const n=Number($('resizeH').value);if(n>=1&&n<=300)$('resizeW').value=Math.max(1,Math.round(n*source.width/source.height));}previewNow();}
 button.onclick=()=>{$('resizeBeadSize').value=$('editorBeadSize')?$('editorBeadSize').value:'2.6';source=clone(state);source.title=$('title').value.trim()||source.title;$('resizeW').value=source.width;$('resizeH').value=source.height;$('resizeRatio').checked=true;$('resizeOriginalLabel').textContent='Original '+source.width+' × '+source.height+centimetres(source)+' · '+count(source).toLocaleString()+' beads';paint($('resizeOriginal'),source);dialog.showModal();previewNow();};
 $('resizeCancel').onclick=()=>dialog.close();$('resizeW').oninput=dimensionsFromWidth;$('resizeH').oninput=dimensionsFromHeight;$('resizeRatio').onchange=dimensionsFromWidth;$('resizeMethod').onchange=previewNow;
 $('resize60cm').onclick=()=>{const size=Math.round(600/Number($('resizeBeadSize').value));if($('resizeRatio').checked){const factor=size/Math.max(source.width,source.height);$('resizeW').value=Math.max(1,Math.round(source.width*factor));$('resizeH').value=Math.max(1,Math.round(source.height*factor));}else{$('resizeW').value=size;$('resizeH').value=size;}previewNow();};
 dialog.querySelectorAll('[data-resize]').forEach(b=>b.onclick=()=>{const size=Number(b.dataset.resize);if($('resizeRatio').checked){const factor=size/Math.max(source.width,source.height);$('resizeW').value=Math.max(1,Math.round(source.width*factor));$('resizeH').value=Math.max(1,Math.round(source.height*factor));}else{$('resizeW').value=size;$('resizeH').value=size;}previewNow();});
 for(const [id,factor]of [['resizeHalf',.5],['resizeDouble',2]])$(id).onclick=()=>{$('resizeW').value=Math.max(1,Math.round(source.width*factor));$('resizeH').value=Math.max(1,Math.round(source.height*factor));previewNow();};
 $('resizeApply').onclick=()=>{if(!preview||$('resizeApply').disabled)return;try{const originals=projects(),original=clone(source);original.projectId=original.projectId||crypto.randomUUID();originals[original.projectId]=original;localStorage.setItem(STORAGE+'-projects',JSON.stringify(originals));const resized={...preview,title:source.title+' — '+preview.width+' × '+preview.height,projectId:crypto.randomUUID()};load(resized);projectList();dialog.close();notice('Resized copy created. Original saved in Your projects; Undo returns to it.');}catch(e){$('resizeMessage').textContent='Could not create the copy: '+e.message+' Download a project backup if browser storage is full.';$('resizeMessage').className='resizeWarning';}};
 document.querySelector('.brand .sub').textContent='Version 10 · Resize designs & inventory';
})();
